name: Compile main.typst

on:
  workflow_dispatch: 
  push:
    branches:
      - main
    paths: ["*.typ", ".github/workflows/typst.yml", "bib.yaml"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile log
        uses: lvignoli/typst-action@main
        with: { source_file: log.typ }

      - name: Compile biblio
        uses: lvignoli/typst-action@main
        with: { source_file: biblio.typ }

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: Update PDFs
          add: '*.pdf'
