name: Compile main.typst

on:
  workflow_dispatch: 
  push:
    branches:
      - main
    paths: ["*.typst", "*.typ", ".github/workflows/typst.yml", "bib.yaml"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Typst
        uses: lvignoli/typst-action@main
        with: { source_file: main.typst }

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: Update main.pdf
          add: main.pdf
